ALTER SESSION SET "_ORACLE_SCRIPT"=true;
    drop user MVC CASCADE;
    create user MVC IDENTIFIED by MVC
     DEFAULT TABLESPACE USERS
     TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE, DBA TO MVC;
     