ALTER SESSION SET "_ORACLE_SCRIPT"=true;
    drop user MIRE CASCADE;
    create user MIRE IDENTIFIED by MIRE
     DEFAULT TABLESPACE USERS
     TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE, DBA TO MIRE;
     