CREATE TABLE SUBJECT(
    NO      NUMBER              NOT NULL,       --순차번호
    S_NUM   VARCHAR(2)     NOT NULL,       --학과번호
    S_NAME  VARCHAR(24)    NOT NULL        --과목명 (한글이 1개당 2바이트)
);
ALTER TABLE SUBHECT ADD CONSTRAINT SUBJECT_PK PRIMARY KEY(NO);
ALTER TABLE SUBHECT ADD CONSTRAINT SUBJECT_UK UNIQUE(S_NUM);

CREATE SEQUENCE SUBJECT_SEQ
    START WITH 1
    INCREMENT BY 1;

INSERT INTO SUBJECT(NO,S_NUM,S_NAME) VALUES(SUBJECT_SEQ.NEXTVAL,'01','컴퓨터 학과');
SELECT * FROM SUBJECT ORDER BY NO ASC; 