--DROP TABLE LEND_RETURN;
CREATE TABLE LEND_RETURN(
IR_CODE         NUMBER(5),
G_CODE          NUMBER(5) NOT NULL,
V_CODE          NUMBER(5) NOT NULL,
I_DATE          DATE,
R_PLAN_DATE     DATE,
I_TOTAL_PAY     NUMBER(7)
);

ALTER TABLE LEND_RETURN
ADD PRIMARY KEY(IR_CODE);

--DROP TABLE HR_VIDEO;
CREATE TABLE HR_VIDEO(
V_CODE          NUMBER(5),
V_TITLE         VARCHAR2(50 BYTE),
V_GENRE         VARCHAR2(30 BYTE),
V_PAY           NUMBER(7),
V_LEND_STATE    NUMBER(1),   
V_MAKE_COMPANY  VARCHAR2(50 BYTE),
V_MAKE_DATE     DATE,
V_VIEW_AGE      NUMBER(1)
);

ALTER TABLE HR_VIDEO
ADD PRIMARY KEY(V_CODE);

--DROP TABLE HR_V_GOGER;
CREATE TABLE HR_V_GOGER(
G_CODE          NUMBER(5),
G_NAME          VARCHAR2(20 BYTE),
G_AGE           NUMBER(3),
G_ADDR          VARCHAR2(50 BYTE),
G_TEL           VARCHAR2(20 BYTE)
);

ALTER TABLE HR_V_GOGER
ADD PRIMARY KEY(G_CODE);

--ALTER TABLE LEND_RETURN
--ADD CONSTRAINT LEND_RETURN_G_CODE_FK FOREIGN KEY (G_CODE) REFERENCES V_GOGER(G_CODE);

--ALTER TABLE LEND_RETURN
--ADD CONSTRAINT LEND_RETURN_V_CODE_FK FOREIGN KEY (V_CODE) REFERENCES V_GOGER(V_CODE);


ALTER TABLE LEND_RETURN
ADD CONSTRAINT LEND_RETURN_G_CODE_FK FOREIGN KEY (G_CODE) REFERENCES HR_V_GOGER(G_CODE);

ALTER TABLE LEND_RETURN
ADD CONSTRAINT LEND_RETURN_V_CODE_FK FOREIGN KEY (V_CODE) REFERENCES HR_VIDEO(V_CODE);
--VALUES(NULL )


--DESC HR_VIDEO;
--SELECT * FROM HR_VIDEO;