SELECT A.FIRST_NAME AS 사원명, B.FIRST_NAME 매니저명
FROM EMPLOYEES A, EMPLOYEES B
WHERE A.MANAGER_ID = B.MANAGER_ID;

SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'ELIZABETH';
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = '148';

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

--1. SALES 부서 소속 사원의 이름과 입사일을 출력하라
SELECT FIRST_NAME, HIRE_DATE
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS  D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_NAME = 'Sales';



--2. 커미션 받는 직원의 이름과 그가속한 부서명을 출력하라.
SELECT FIRST_NAME , DEPARTMENT_NAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE COMMISSION_PCT IS NOT NULL;

--3. FIRST NAME GUY과 동일한 부서에서 근무하는 직원의 이름과 부서 번호를 출력하라. 
SELECT E.FIRST_NAME, E.DEPARTMENT_ID
FROM EMPLOYEES E
JOIN (
    SELECT DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE FIRST_NAME = 'Guy'
) A ON E.DEPARTMENT_ID = A.DEPARTMENT_ID;

SELECT FIRST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
    WHERE DEPARTMENT_ID = (
    SELECT DEPARTMENT_ID 
    FROM EMPLOYEES 
    WHERE FIRST_NAME = 'Guy'
);

