SELECT * FROM EMPLOYEES;
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 198;


DROP TABLE EMP01;

CREATE TABLE EMP01
AS
SELECT * FROM EMPLOYEES;

SELECT * FROM EMP01;
SELECT * FROM EMP01 WHERE EMPLOYEE_ID = 198;