--삭제
DROP TABLE EMP01;
--테이블 생성
CREATE TABLE EMP01(
    EMPNO NUMBER(4) NOT NULL,
    ENAME VARCHAR2(10) NOT NULL,
    JOB   VARCHAR2(9),
    MGR NUMBER(4), 
    HIREDATE DATE NOT NULL,
    SAL NUMBER (7,2) NOT NULL,
    COMM NUMBER (7,2),
    DEPTNO NUMBER (2) NOT NULL
);

-- 데이터 추가
INPUT INTO (
    EMPNO
    ENAME
    JOB
    MGR
    HIREDATE
    SAL
    COMM
    DEPTNO
)
VALUE(
    EMPNO NUMBER(4) NOT NULL,
    ENAME VARCHAR2(10) NOT NULL,
    JOB   VARCHAR2(9),
    MGR NUMBER(4), 
    HIREDATE DATE NOT NULL,
    SAL NUMBER (7,2) NOT NULL,
    COMM NUMBER (7,2),
    DEPTNO NUMBER (2) NOT NULL

);

