DROP TABLE CUSTOMERS; 
DROP TABLE CUSTOMERS2; 

CREATE TABLE CUSTOMERS2 (
    CU_NO NUMBER(10) NOT NULL,
    CUSTUMER_CD CHAR(7) NOT NULL,
    CUSTOMER_NAME NVARCHAR2(10) NOT NULL,
    GENDER CHAR(1) NOT NULL,
    BIRTH_DAY CHAR(8) NOT NULL,
    PHONE_NUMBER VARCHAR2(16),
    EMAIL VARCHAR2(30),
    CUSTOMER_POINT NUMBER(10)
);
 --ALTER TABLE CUSTOMERS2 DROP CONSTRAINT CUSTOMER_PK;
 ALTER TABLE CUSTOMERS2 ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY (CU_NO);
 ALTER TABLE CUSTOMERS2 ADD CONSTRAINT GENDER_CHECK CHECK (GENDER IN ('M', 'F'));

CREATE SEQUENCE CUSTOMERS2_SEQ 
START WITH 1
INCREMENT BY 1; 

INSERT INTO CUSTOMERS2(
    CU_NO,
    CUSTUMER_CD,
    CUSTOMER_NAME,
    GENDER,
    BIRTH_DAY,
    PHONE_NUMBER,
    EMAIL,
    CUSTOMER_POINT 
)   
VALUES(
    CUSTOMERS2_SEQ.NEXTVAL,
    'ASDF134',
    '±è±è±è',
    'M',
    '19971212',
    '010-3339-3339',
    'KIMKIMKIM1@GMAIL.COM',
    90102030
);

INSERT INTO CUSTOMERS2
VALUES(
    CUSTOMERS2_SEQ.NEXTVAL,
    'ASDF133',
    '¹Ú¹Ú¹Ú',
    'F',
    '19971213',
    '010-3339-3330',
    '2222IM1@GMAIL.COM',
    90102032
);
INSERT INTO CUSTOMERS2
VALUES(
    CUSTOMERS2_SEQ.NEXTVAL,
    'ASDF134',
    '±è±è±è',
    'M',
    '19971212',
    '010-3339-3339',
    'KIMKIMKIM1@GMAIL.COM',
    90102030
);

INSERT INTO CUSTOMERS2(
    CU_NO,
    CUSTUMER_CD,
    CUSTOMER_NAME,
    GENDER,
    BIRTH_DAY
)   
VALUES(
    CUSTOMERS2_SEQ.NEXTVAL,
    'ASD234',
    'ADFµðµðµù',
    'M',
    '19971212'
);
 --ALTER TABLE CUSTOMERS2 MODIFY(CUSTOMER_NAME NVARCHAR2(15));
SELECT * FROM TAB;
SELECT * FROM CUSTOMERS2;
DESC CUSTOMERS2;

--DELETE FROM CUSTOMERS2;
--COMMIT;

